---
kind: pipeline
type: docker
name: Build Docker Image (s2oj-db)

steps:
  - name: tags
    image: alpine
    commands:
      - echo -n "latest, $DRONE_BRANCH, ${DRONE_COMMIT_SHA:0:8}" > .tags

  - name: docker
    image: plugins/docker
    settings:
      registry: git.m.ac
      repo: git.m.ac/baoshuo/s2oj-db
      context: db
      dockerfile: db/Dockerfile
      username: baoshuo
      password:
        from_secret: GITMAC_SECRET
    when:
      event: push
      branch: master

---
kind: pipeline
type: docker
name: Build Docker Image (s2oj-judger)

steps:
  - name: tags
    image: alpine
    commands:
      - echo -n "latest, $DRONE_BRANCH, ${DRONE_COMMIT_SHA:0:8}" > .tags

  - name: docker
    image: plugins/docker
    settings:
      registry: git.m.ac
      repo: git.m.ac/baoshuo/s2oj-judger
      context: judger
      dockerfile: judger/Dockerfile
      username: baoshuo
      password:
        from_secret: GITMAC_SECRET
    when:
      event: push
      branch: master

---
kind: pipeline
type: docker
name: Build Docker Image (s2oj-web)

steps:
  - name: tags
    image: alpine
    commands:
      - echo -n "latest, $DRONE_BRANCH, ${DRONE_COMMIT_SHA:0:8}" > .tags

  - name: docker
    image: plugins/docker
    settings:
      registry: git.m.ac
      repo: git.m.ac/baoshuo/s2oj-web
      dockerfile: web/Dockerfile
      username: baoshuo
      password:
        from_secret: GITMAC_SECRET
    when:
      event: push
      branch: master
