---
kind: pipeline
type: docker
name: Build Docker Image (s2oj-db)

trigger:
  branch:
  - master

steps:
  - name: tags
    image: alpine
    commands:
      - echo -n "latest, $DRONE_BRANCH, ${DRONE_COMMIT_SHA:0:8}" > .tags

  - name: docker
    image: plugins/docker
    settings:
      registry: git.m.ac
      repo: git.m.ac/baoshuo/s2oj-db
      context: db
      dockerfile: db/Dockerfile
      username: baoshuo
      password:
        from_secret: GITMAC_SECRET
      cache_from: git.m.ac/baoshuo/s2oj-db:latest
    when:
      event: push
      branch: master

---
kind: pipeline
type: docker
name: Build Docker Image (s2oj-judger)

trigger:
  branch:
  - master

steps:
  - name: tags
    image: alpine
    commands:
      - echo -n "latest, $DRONE_BRANCH, ${DRONE_COMMIT_SHA:0:8}" > .tags

  - name: docker
    image: plugins/docker
    settings:
      registry: git.m.ac
      repo: git.m.ac/baoshuo/s2oj-judger
      context: judger
      dockerfile: judger/Dockerfile
      username: baoshuo
      password:
        from_secret: GITMAC_SECRET
      cache_from: git.m.ac/baoshuo/s2oj-judger:latest
    when:
      event: push
      branch: master

---
kind: pipeline
type: docker
name: Build Docker Image (s2oj-web)

trigger:
  branch:
  - master

steps:
  - name: tags
    image: alpine
    commands:
      - echo -n "latest, $DRONE_BRANCH, ${DRONE_COMMIT_SHA:0:7}" > .tags

  - name: version
    image: alpine
    commands:
      - sed -i "s/'s2oj-version' => 'dev'/'s2oj-version' => '${DRONE_COMMIT_SHA:0:7}'/g" web/app/.default-config.php

  - name: docker
    image: plugins/docker
    settings:
      registry: git.m.ac
      repo: git.m.ac/baoshuo/s2oj-web
      dockerfile: web/Dockerfile
      username: baoshuo
      password:
        from_secret: GITMAC_SECRET
      cache_from: git.m.ac/baoshuo/s2oj-web:latest
    when:
      event: push
      branch: master
